#############################################################################
# Makefile for building: QTMSER.app/Contents/MacOS/QTMSER
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  QTMSER.pro
# Template: app
# Command: /Users/hidog/code/qt5-build/qtbase/bin/qmake -o QTMSER.xcodeproj/project.pbxproj QTMSER.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Users/hidog/code/qt5-build/qtbase/bin/qmake
QTMSER.xcodeproj/project.pbxproj: QTMSER.pro ../../QT5/qtbase/mkspecs/macx-clang/qmake.conf ../../QT5/qtbase/mkspecs/features/spec_pre.prf \
		../../qt5-build/qtbase/mkspecs/qdevice.pri \
		../../QT5/qtbase/mkspecs/features/device_config.prf \
		../../QT5/qtbase/mkspecs/common/unix.conf \
		../../QT5/qtbase/mkspecs/common/mac.conf \
		../../QT5/qtbase/mkspecs/common/macx.conf \
		../../QT5/qtbase/mkspecs/common/sanitize.conf \
		../../QT5/qtbase/mkspecs/common/gcc-base.conf \
		../../QT5/qtbase/mkspecs/common/gcc-base-mac.conf \
		../../QT5/qtbase/mkspecs/common/clang.conf \
		../../QT5/qtbase/mkspecs/common/clang-mac.conf \
		../../qt5-build/qtbase/mkspecs/qconfig.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext__clip2tri.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext__clipper.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext__poly2tri.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext_freetype.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext_libpng.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext_openwnn.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext_pcre2.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext_pinyin.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext_qmapboxgl.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext_tcime.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3danimation.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dcore.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dextras.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dinput.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dlogic.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquick.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3drender.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_3drender_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_bluetooth.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_bootstrap_dbus_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_charts.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_charts_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_core_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_datavisualization.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_dbus.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_designer.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_designer_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_gamepad.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_help.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_help_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_location.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_location_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_macextras.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_macextras_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_network_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_networkauth.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_nfc.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_nfc_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_opengl_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_positioning.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_positioning_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_positioningquick.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_purchasing.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_qml.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3d.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3drender.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_repparser.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_repparser_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_script.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_script_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_scripttools.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_scxml.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_scxml_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_sensors.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_sensors_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_serialbus.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_serialport.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_service_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_sql.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_svg.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_svg_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_texttospeech.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_uiplugin.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_uitools.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_uitools_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_webchannel.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_websockets.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_webview.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_webview_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_balsam.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_canbusutil.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_lconvert.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_lprodump.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_lrelease-pro.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_lrelease.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_lupdate-pro.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_lupdate.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_meshdebug.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qcollectiongenerator.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qgltf.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qhelpgenerator.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qlalr.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qml.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlcachegen.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlformat.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlimportscanner.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmljs.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmllint.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlmin.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlplugindump.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlpreview.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlprofiler.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlscene.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmltestrunner.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmltyperegistrar.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qscxmlc.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qtattributionsscanner.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qvkgen.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_repc.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_uic.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri \
		../../QT5/qtbase/mkspecs/features/qt_functions.prf \
		../../QT5/qtbase/mkspecs/features/qt_config.prf \
		../../QT5/qtbase/mkspecs/macx-clang/qmake.conf \
		../../QT5/qtbase/mkspecs/macx-xcode/qmake.conf \
		../../QT5/qtbase/mkspecs/features/spec_post.prf \
		../../QT5/qtbase/mkspecs/features/exclusive_builds.prf \
		../../QT5/qtbase/mkspecs/features/mac/sdk.prf \
		../../QT5/qtbase/mkspecs/features/toolchain.prf \
		../../QT5/qtbase/mkspecs/features/mac/toolchain.prf \
		../../QT5/qtbase/mkspecs/features/default_pre.prf \
		../../QT5/qtbase/mkspecs/features/mac/default_pre.prf \
		../../QT5/qtbase/mkspecs/features/resolve_config.prf \
		../../QT5/qtbase/mkspecs/features/default_post.prf \
		../../QT5/qtbase/mkspecs/features/mac/default_post.prf \
		../../QT5/qtbase/mkspecs/features/mac/objective_c.prf \
		../../QT5/qtbase/mkspecs/features/mac/mac.prf \
		../../QT5/qtbase/mkspecs/features/warn_on.prf \
		../../QT5/qtbase/mkspecs/features/qt.prf \
		../../QT5/qtbase/mkspecs/features/resources_functions.prf \
		../../QT5/qtbase/mkspecs/features/resources.prf \
		../../QT5/qtbase/mkspecs/features/moc.prf \
		../../QT5/qtbase/mkspecs/features/unix/opengl.prf \
		../../QT5/qtbase/mkspecs/features/uic.prf \
		../../QT5/qtbase/mkspecs/features/unix/thread.prf \
		../../QT5/qtbase/mkspecs/features/qmake_use.prf \
		../../QT5/qtbase/mkspecs/features/file_copies.prf \
		../../QT5/qtbase/mkspecs/features/mac/rez.prf \
		../../QT5/qtbase/mkspecs/features/mac/asset_catalogs.prf \
		../../QT5/qtbase/mkspecs/features/testcase_targets.prf \
		../../QT5/qtbase/mkspecs/features/exceptions.prf \
		../../QT5/qtbase/mkspecs/features/yacc.prf \
		../../QT5/qtbase/mkspecs/features/lex.prf \
		QTMSER.pro \
		../../qt5-build/qtbase/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../qt5-build/qtbase/lib/QtGui.framework/Resources/QtGui.prl \
		../../qt5-build/qtbase/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o QTMSER.xcodeproj/project.pbxproj QTMSER.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
../../QT5/qtbase/mkspecs/features/spec_pre.prf:
../../qt5-build/qtbase/mkspecs/qdevice.pri:
../../QT5/qtbase/mkspecs/features/device_config.prf:
../../QT5/qtbase/mkspecs/common/unix.conf:
../../QT5/qtbase/mkspecs/common/mac.conf:
../../QT5/qtbase/mkspecs/common/macx.conf:
../../QT5/qtbase/mkspecs/common/sanitize.conf:
../../QT5/qtbase/mkspecs/common/gcc-base.conf:
../../QT5/qtbase/mkspecs/common/gcc-base-mac.conf:
../../QT5/qtbase/mkspecs/common/clang.conf:
../../QT5/qtbase/mkspecs/common/clang-mac.conf:
../../qt5-build/qtbase/mkspecs/qconfig.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext__clip2tri.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext__clipper.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext__poly2tri.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext_freetype.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext_libpng.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext_openwnn.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext_pcre2.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext_pinyin.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext_qmapboxgl.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext_tcime.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3danimation.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3danimation_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dcore.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dcore_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dextras.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dextras_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dinput.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dinput_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dlogic.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquick.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquick_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickextras.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickinput.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickrender.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3drender.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_3drender_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_bluetooth.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_bootstrap_dbus_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_charts.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_charts_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_concurrent.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_concurrent_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_core.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_core_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_datavisualization.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_dbus.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_dbus_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_designer.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_designer_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_gamepad.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_gamepad_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_gui.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_gui_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_help.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_help_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_location.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_location_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_macextras.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_macextras_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_multimedia.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_multimedia_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_network.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_network_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_networkauth.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_networkauth_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_nfc.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_nfc_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_opengl.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_opengl_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_openglextensions.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_positioning.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_positioning_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_positioningquick.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_printsupport.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_purchasing.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_purchasing_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_qml.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_qml_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmlmodels.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmltest.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmltest_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3d.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3d_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3drender.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3dutils.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quick_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quickwidgets.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_remoteobjects.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_repparser.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_repparser_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_script.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_script_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_scripttools.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_scripttools_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_scxml.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_scxml_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_sensors.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_sensors_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_serialbus.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_serialbus_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_serialport.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_serialport_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_service_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_sql.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_sql_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_svg.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_svg_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_testlib.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_testlib_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_texttospeech.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_uiplugin.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_uitools.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_uitools_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_webchannel.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_webchannel_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_websockets.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_websockets_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_webview.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_webview_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_widgets.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_widgets_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_xml.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_xml_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_balsam.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_canbusutil.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_lconvert.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_lprodump.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_lrelease-pro.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_lrelease.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_lupdate-pro.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_lupdate.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_meshdebug.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qcollectiongenerator.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qgltf.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qhelpgenerator.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qlalr.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qml.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlcachegen.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlformat.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlimportscanner.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmljs.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmllint.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlmin.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlplugindump.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlpreview.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlprofiler.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmlscene.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmltestrunner.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qmltyperegistrar.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qscxmlc.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qtattributionsscanner.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qvkgen.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_repc.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_syncqt.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_uic.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri:
../../QT5/qtbase/mkspecs/features/qt_functions.prf:
../../QT5/qtbase/mkspecs/features/qt_config.prf:
../../QT5/qtbase/mkspecs/macx-clang/qmake.conf:
../../QT5/qtbase/mkspecs/macx-xcode/qmake.conf:
../../QT5/qtbase/mkspecs/features/spec_post.prf:
../../QT5/qtbase/mkspecs/features/exclusive_builds.prf:
../../QT5/qtbase/mkspecs/features/mac/sdk.prf:
../../QT5/qtbase/mkspecs/features/toolchain.prf:
../../QT5/qtbase/mkspecs/features/mac/toolchain.prf:
../../QT5/qtbase/mkspecs/features/default_pre.prf:
../../QT5/qtbase/mkspecs/features/mac/default_pre.prf:
../../QT5/qtbase/mkspecs/features/resolve_config.prf:
../../QT5/qtbase/mkspecs/features/default_post.prf:
../../QT5/qtbase/mkspecs/features/mac/default_post.prf:
../../QT5/qtbase/mkspecs/features/mac/objective_c.prf:
../../QT5/qtbase/mkspecs/features/mac/mac.prf:
../../QT5/qtbase/mkspecs/features/warn_on.prf:
../../QT5/qtbase/mkspecs/features/qt.prf:
../../QT5/qtbase/mkspecs/features/resources_functions.prf:
../../QT5/qtbase/mkspecs/features/resources.prf:
../../QT5/qtbase/mkspecs/features/moc.prf:
../../QT5/qtbase/mkspecs/features/unix/opengl.prf:
../../QT5/qtbase/mkspecs/features/uic.prf:
../../QT5/qtbase/mkspecs/features/unix/thread.prf:
../../QT5/qtbase/mkspecs/features/qmake_use.prf:
../../QT5/qtbase/mkspecs/features/file_copies.prf:
../../QT5/qtbase/mkspecs/features/mac/rez.prf:
../../QT5/qtbase/mkspecs/features/mac/asset_catalogs.prf:
../../QT5/qtbase/mkspecs/features/testcase_targets.prf:
../../QT5/qtbase/mkspecs/features/exceptions.prf:
../../QT5/qtbase/mkspecs/features/yacc.prf:
../../QT5/qtbase/mkspecs/features/lex.prf:
QTMSER.pro:
../../qt5-build/qtbase/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../qt5-build/qtbase/lib/QtGui.framework/Resources/QtGui.prl:
../../qt5-build/qtbase/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o QTMSER.xcodeproj/project.pbxproj QTMSER.pro -spec macx-xcode

qmake_all: FORCE

