#############################################################################
# Makefile for building: QTMSER.app/Contents/MacOS/QTMSER
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  QTMSER.pro
# Template: app
# Command: /Users/hidog/code/qt5-build/qtbase/bin/qmake -o QTMSER.xcodeproj/project.pbxproj QTMSER.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Users/hidog/code/qt5-build/qtbase/bin/qmake
QTMSER.xcodeproj/project.pbxproj: QTMSER.pro ../../QT5/qtbase/mkspecs/macx-clang/qmake.conf ../../QT5/qtbase/mkspecs/features/spec_pre.prf \
		../../qt5-build/qtbase/mkspecs/qdevice.pri \
		../../QT5/qtbase/mkspecs/features/device_config.prf \
		../../QT5/qtbase/mkspecs/common/unix.conf \
		../../QT5/qtbase/mkspecs/common/mac.conf \
		../../QT5/qtbase/mkspecs/common/macx.conf \
		../../QT5/qtbase/mkspecs/common/sanitize.conf \
		../../QT5/qtbase/mkspecs/common/gcc-base.conf \
		../../QT5/qtbase/mkspecs/common/gcc-base-mac.conf \
		../../QT5/qtbase/mkspecs/common/clang.conf \
		../../QT5/qtbase/mkspecs/common/clang-mac.conf \
		../../qt5-build/qtbase/mkspecs/qconfig.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext_freetype.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext_libpng.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_ext_pcre2.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_accessibility_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_bootstrap_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_clipboard_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_concurrent.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_concurrent_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_core.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_core_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_dbus.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_dbus_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_dbus.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_devicediscovery_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_edid_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_eventdispatcher_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_fb_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_fontdatabase_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_graphics_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_gui.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_gui_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_network.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_network_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_opengl.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_opengl_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_openglextensions.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_openglextensions_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_platformcompositor_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_printsupport.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_printsupport_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_service_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_service_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_sql.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_sql_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_sql.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_testlib.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_testlib_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_theme_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_widgets.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_widgets_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_xml.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_xml_private.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_cocoaprintersupport.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_plugin_cocoaprintersupport.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qcocoa.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qcocoa.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qgenericbearer.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qgif.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qgif.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qico.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qjpeg.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qmacstyle.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qmacstyle.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qminimal.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qminimal.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qoffscreen.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qsqlite.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qtuiotouchplugin.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qxdgdesktopportal.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_moc.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qlalr.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_qvkgen.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_rcc.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_tracegen.pri \
		../../qt5-build/qtbase/mkspecs/modules/qt_tool_uic.pri \
		../../QT5/qtbase/mkspecs/features/qt_functions.prf \
		../../QT5/qtbase/mkspecs/features/qt_config.prf \
		../../QT5/qtbase/mkspecs/macx-clang/qmake.conf \
		../../QT5/qtbase/mkspecs/macx-xcode/qmake.conf \
		../../QT5/qtbase/mkspecs/features/spec_post.prf \
		../../QT5/qtbase/mkspecs/features/exclusive_builds.prf \
		../../QT5/qtbase/mkspecs/features/mac/sdk.prf \
		../../QT5/qtbase/mkspecs/features/toolchain.prf \
		../../QT5/qtbase/mkspecs/features/mac/toolchain.prf \
		../../QT5/qtbase/mkspecs/features/default_pre.prf \
		../../QT5/qtbase/mkspecs/features/mac/default_pre.prf \
		../../QT5/qtbase/mkspecs/features/resolve_config.prf \
		../../QT5/qtbase/mkspecs/features/default_post.prf \
		../../QT5/qtbase/mkspecs/features/mac/default_post.prf \
		../../QT5/qtbase/mkspecs/features/mac/objective_c.prf \
		../../QT5/qtbase/mkspecs/features/mac/mac.prf \
		../../QT5/qtbase/mkspecs/features/warn_on.prf \
		../../QT5/qtbase/mkspecs/features/qt.prf \
		../../QT5/qtbase/mkspecs/features/resources_functions.prf \
		../../QT5/qtbase/mkspecs/features/resources.prf \
		../../QT5/qtbase/mkspecs/features/moc.prf \
		../../QT5/qtbase/mkspecs/features/unix/opengl.prf \
		../../QT5/qtbase/mkspecs/features/uic.prf \
		../../QT5/qtbase/mkspecs/features/unix/thread.prf \
		../../QT5/qtbase/mkspecs/features/qmake_use.prf \
		../../QT5/qtbase/mkspecs/features/file_copies.prf \
		../../QT5/qtbase/mkspecs/features/mac/rez.prf \
		../../QT5/qtbase/mkspecs/features/mac/asset_catalogs.prf \
		../../QT5/qtbase/mkspecs/features/testcase_targets.prf \
		../../QT5/qtbase/mkspecs/features/exceptions.prf \
		../../QT5/qtbase/mkspecs/features/yacc.prf \
		../../QT5/qtbase/mkspecs/features/lex.prf \
		QTMSER.pro \
		../../qt5-build/qtbase/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../qt5-build/qtbase/lib/QtGui.framework/Resources/QtGui.prl \
		../../qt5-build/qtbase/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o QTMSER.xcodeproj/project.pbxproj QTMSER.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
../../QT5/qtbase/mkspecs/features/spec_pre.prf:
../../qt5-build/qtbase/mkspecs/qdevice.pri:
../../QT5/qtbase/mkspecs/features/device_config.prf:
../../QT5/qtbase/mkspecs/common/unix.conf:
../../QT5/qtbase/mkspecs/common/mac.conf:
../../QT5/qtbase/mkspecs/common/macx.conf:
../../QT5/qtbase/mkspecs/common/sanitize.conf:
../../QT5/qtbase/mkspecs/common/gcc-base.conf:
../../QT5/qtbase/mkspecs/common/gcc-base-mac.conf:
../../QT5/qtbase/mkspecs/common/clang.conf:
../../QT5/qtbase/mkspecs/common/clang-mac.conf:
../../qt5-build/qtbase/mkspecs/qconfig.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext_freetype.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext_libpng.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_ext_pcre2.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_accessibility_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_bootstrap_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_clipboard_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_concurrent.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_concurrent_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_concurrent.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_core.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_core_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_core.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_dbus.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_dbus_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_dbus.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_devicediscovery_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_edid_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_eventdispatcher_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_fb_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_fontdatabase_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_graphics_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_gui.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_gui_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_gui.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_network.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_network_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_network.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_opengl.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_opengl_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_opengl.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_openglextensions.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_openglextensions_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_openglextensions.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_platformcompositor_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_printsupport.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_printsupport_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_printsupport.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_service_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_service_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_sql.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_sql_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_sql.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_testlib.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_testlib_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_testlib.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_theme_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_widgets.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_widgets_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_widgets.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_xml.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_lib_xml_private.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_lib_xml.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_cocoaprintersupport.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_plugin_cocoaprintersupport.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qcocoa.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qcocoa.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qgenericbearer.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qgif.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qgif.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qico.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qico.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qjpeg.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qmacstyle.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qmacstyle.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qminimal.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qminimal.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qoffscreen.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qsqlite.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qsqlite.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qtuiotouchplugin.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../qt5-build/qtbase/mkspecs/modules-inst/qt_plugin_qxdgdesktopportal.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_moc.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qlalr.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_qvkgen.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_rcc.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_syncqt.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_tracegen.pri:
../../qt5-build/qtbase/mkspecs/modules/qt_tool_uic.pri:
../../QT5/qtbase/mkspecs/features/qt_functions.prf:
../../QT5/qtbase/mkspecs/features/qt_config.prf:
../../QT5/qtbase/mkspecs/macx-clang/qmake.conf:
../../QT5/qtbase/mkspecs/macx-xcode/qmake.conf:
../../QT5/qtbase/mkspecs/features/spec_post.prf:
../../QT5/qtbase/mkspecs/features/exclusive_builds.prf:
../../QT5/qtbase/mkspecs/features/mac/sdk.prf:
../../QT5/qtbase/mkspecs/features/toolchain.prf:
../../QT5/qtbase/mkspecs/features/mac/toolchain.prf:
../../QT5/qtbase/mkspecs/features/default_pre.prf:
../../QT5/qtbase/mkspecs/features/mac/default_pre.prf:
../../QT5/qtbase/mkspecs/features/resolve_config.prf:
../../QT5/qtbase/mkspecs/features/default_post.prf:
../../QT5/qtbase/mkspecs/features/mac/default_post.prf:
../../QT5/qtbase/mkspecs/features/mac/objective_c.prf:
../../QT5/qtbase/mkspecs/features/mac/mac.prf:
../../QT5/qtbase/mkspecs/features/warn_on.prf:
../../QT5/qtbase/mkspecs/features/qt.prf:
../../QT5/qtbase/mkspecs/features/resources_functions.prf:
../../QT5/qtbase/mkspecs/features/resources.prf:
../../QT5/qtbase/mkspecs/features/moc.prf:
../../QT5/qtbase/mkspecs/features/unix/opengl.prf:
../../QT5/qtbase/mkspecs/features/uic.prf:
../../QT5/qtbase/mkspecs/features/unix/thread.prf:
../../QT5/qtbase/mkspecs/features/qmake_use.prf:
../../QT5/qtbase/mkspecs/features/file_copies.prf:
../../QT5/qtbase/mkspecs/features/mac/rez.prf:
../../QT5/qtbase/mkspecs/features/mac/asset_catalogs.prf:
../../QT5/qtbase/mkspecs/features/testcase_targets.prf:
../../QT5/qtbase/mkspecs/features/exceptions.prf:
../../QT5/qtbase/mkspecs/features/yacc.prf:
../../QT5/qtbase/mkspecs/features/lex.prf:
QTMSER.pro:
../../qt5-build/qtbase/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../qt5-build/qtbase/lib/QtGui.framework/Resources/QtGui.prl:
../../qt5-build/qtbase/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o QTMSER.xcodeproj/project.pbxproj QTMSER.pro -spec macx-xcode

qmake_all: FORCE

