#############################################################################
# Makefile for building: QTMSER.app/Contents/MacOS/QTMSER
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  QTMSER.pro
# Template: app
# Command: /Users/hidog/code/qt5-build/qtbase/bin/qmake -o QTMSER.xcodeproj/project.pbxproj QTMSER.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

MOC       = /Users/hidog/code/qt5-build/qtbase/bin/moc
UIC       = /Users/hidog/code/test/QTMSER/uic_wrapper.sh
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH       = -I. -I../../qt5-build/qtbase/include -I../../qt5-build/qtbase/include/QtWidgets -I../../qt5-build/qtbase/include/QtGui -I../../qt5-build/qtbase/include/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../QT5/qtbase/mkspecs/macx-clang -F/Users/hidog/code/qt5-build/qtbase/lib
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: moc_predefs.h moc_mainwindow.cpp ui_mainwindow.h
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../QT5/qtbase/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h ../../QT5/qtbase/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		../../qt5-build/qtbase/include/QtWidgets/QMainWindow \
		../../qt5-build/qtbase/include/QtWidgets/QLabel \
		moc_predefs.h \
		../../qt5-build/qtbase/bin/moc
	/Users/hidog/code/qt5-build/qtbase/bin/moc $(DEFINES) --include /Users/hidog/code/test/QTMSER/moc_predefs.h -I/Users/hidog/code/QT5/qtbase/mkspecs/macx-clang -I/Users/hidog/code/test/QTMSER -I/Users/hidog/code/qt5-build/qtbase/include -I/Users/hidog/code/qt5-build/qtbase/include/QtWidgets -I/Users/hidog/code/qt5-build/qtbase/include/QtGui -I/Users/hidog/code/qt5-build/qtbase/include/QtCore -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/hidog/code/qt5-build/qtbase/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../qt5-build/qtbase/bin/uic
	/Users/hidog/code/test/QTMSER/uic_wrapper.sh mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

